;Install.ini for EPSON Advanced Printer Driver for TM-T88V Ver.5

[Package]
Title	= EPSON Advanced Printer Driver for TM-T88V Ver.5
Version	= 5.13.0.0
Preview	= 5.13.0.0

[Common]
Device			= TM-T88V
DriverInf		= TMPTR_TM-T88V.INF

DriverFolderName	= Driver
DriverInf32			= EA5INSTMT88V.INF
DriverInf64			= EA5INSTMT88V.INF
DriverNameList		= EPSON TM-T88V Receipt5
LangageMonitorName	= EPSON TM-T88V Receipt5 LM
LangageMonitorFiles	= EA5LMTMT88V.DLL:EA5LMTMT88V.dat
APD4DriverNames		= EPSON TM-T88V Receipt%Lang%4

CheckAPD4Version	= 1

SetupLogEnable		= 1
SetupLogPath		= 
SetupLogFileName	= Setup.log

[Plugin]
PluginPackageName32				= UtilityPac32.msi
PluginPackageName64				= UtilityPac64.msi
DeviceUtilityShortName			= TM88VUTL
DeviceUtilityInstallerFolder	= TM-T88V Utility
DeviceUtilityInstallerExe		= setup.exe

[DeviceUtility]
DeviceUtilityInstallPath		= epson\TM-T88V Software\TM88VUTL
DeviceUtilityProgramName		= TM-T88V Utility
DeviceUtilityFollowVersion		= 1.40
DeviceUtilityExecName			= TM88VUTL.exe
DeviceUtilityShortcutName		= APD5 Utility for TM-T88V
